-- SQL Dump generated by PowerShell
-- Regions
INSERT INTO wp_eve_regions (id, region_name) VALUES (10000019, 'A821-A');

-- Constellations
INSERT INTO wp_eve_constellations (id, constellation_name, region_id) VALUES (20000239, '6I-9Y2', 10000019);
INSERT INTO wp_eve_constellations (id, constellation_name, region_id) VALUES (20000238, '826-A5', 10000019);

-- Systems
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001620, 'E-RPGP', -0.03, 20000239);
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001623, 'KER-EU', -0.04, 20000239);
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001622, 'NSE-U1', -0.02, 20000239);
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001619, 'R79-I7', -0.04, 20000239);
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001618, 'UC-X28', -0.03, 20000239);
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001621, 'ZV-KZO', -0.02, 20000239);
INSERT INTO wp_eve_systems (id, system_name, security_status, constellation_id) VALUES (30001615, '2RV-06', -0.08, 20000238);
